version: '3.7'
services:
  postgres:
    container_name: postgre
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped