version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka_1:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka_1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.152.12
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      JMX_PORT: 9999
    volumes:
      - ./data1:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
  kafka_2:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka_2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.152.12
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9988
    volumes:
      - ./data2:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
  kafka_3:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: kafka_3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 10.0.152.12
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9977
    volumes:
      - ./data3:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: hlebalbau/kafka-manager:2.0.0.2
    environment:
        ZK_HOSTS: zookeeper:2181
        KAFKA_BROKERS: kafka_1:9092,kafka_2:9093,kafka_3:9094
        APPLICATION_SECRET: "random-secret"
    ports:
      - "9000:9000"
    command: -Dpidfile.path=/dev/null