version: '3'
services:
  jenkins:
    image: ghcr.io/helm/chartmuseum:v0.13.1
    container_name: chartmuseum
    restart: always
    user: root
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
    volumes:
      - /opt/charts:/charts



