version: "3"
services:
   redis:
     image: redis:5
     container_name: redis_for_kline_test
     command: redis-server /etc/redis.conf
     volumes:
       - "./data:/data"
       - "./redis.conf:/etc/redis.conf"
       - "./sock:/tmp/"
     ports:
       - "6379:6379"
     restart: always
     ulimits:
       nofile:
         soft: 65535
         hard: 65535